zuul:
   sensitiveHeaders:
   prefix: /api   
   
spring:
   application:
      name: zuul-gateway
      
eureka:
   instance:
      preferIpAddress: true
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
         defaultZone: http://172.31.15.55:8761/eureka

server:
   port: 8762

ribbon:
   ConnectTimeout: 20000
   ReadTimeout: 20000

---

spring:
   profiles: dev

eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8761/eureka